# Generated by Django 4.2.27 on 2026-01-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='tips',
        ),
        migrations.AddField(
            model_name='exercise',
            name='tips_negative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tips_points',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tips_positive',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tips_setup',
            field=models.TextField(blank=True),
        ),
    ]
