# Generated by Django 4.2.27 on 2026-01-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0002_remove_exercise_tips_exercise_tips_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
